[package]
name = "segmentdesignweb-sigma"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
rayon = "1.5.3"
segmentdesign-core = { path = "../core" }
