import normalizesegmentdesignDirectives from './lib/normalizesegmentdesignDirectives'
import expandsegmentdesignAtRules from './lib/expandsegmentdesignAtRules'
import expandApplyAtRules from './lib/expandApplyAtRules'
import evaluatesegmentdesignFunctions from './lib/evaluatesegmentdesignFunctions'
import substituteScreenAtRules from './lib/substituteScreenAtRules'
import resolveDefaultsAtRules from './lib/resolveDefaultsAtRules'
import collapseAdjacentRules from './lib/collapseAdjacentRules'
import collapseDuplicateDeclarations from './lib/collapseDuplicateDeclarations'
import partitionApplyAtRules from './lib/partitionApplyAtRules'
import detectNesting from './lib/detectNesting'
import { createContext } from './lib/setupContextUtils'
import { issueFlagNotices } from './featureFlags'

export default function processsegmentdesignFeatures(setupContext) {
  return async function (root, result) {
    let { segmentdesignDirectives, applyDirectives } = normalizesegmentdesignDirectives(root)

    detectNesting()(root, result)

    // Partition apply rules that are found in the css
    // itself.
    partitionApplyAtRules()(root, result)

    let context = setupContext({
      segmentdesignDirectives,
      applyDirectives,
      registerDependency(dependency) {
        result.messages.push({
          plugin: 'segmentdesign',
          parent: result.opts.from,
          ...dependency,
        })
      },
      createContext(segmentdesignConfig, changedContent) {
        return createContext(segmentdesignConfig, changedContent, root)
      },
    })(root, result)

    if (context.segmentdesignConfig.separator === '-') {
      throw new Error(
        "The '-' character cannot be used as a custom separator in JIT mode due to parsing ambiguity. Please use another character like '_' instead."
      )
    }

    issueFlagNotices(context.segmentdesignConfig)

    await expandsegmentdesignAtRules(context)(root, result)

    // Partition apply rules that are generated by
    // addComponents, addUtilities and so on.
    partitionApplyAtRules()(root, result)
    expandApplyAtRules(context)(root, result)
    evaluatesegmentdesignFunctions(context)(root, result)
    substituteScreenAtRules(context)(root, result)
    resolveDefaultsAtRules(context)(root, result)
    collapseAdjacentRules(context)(root, result)
    collapseDuplicateDeclarations(context)(root, result)
  }
}
